# Generated by Django 4.1.5 on 2023-01-17 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_factory_number', models.CharField(max_length=256, verbose_name='Зав. № машины')),
                ('machine_model', models.CharField(max_length=256, verbose_name='Модель техники')),
                ('engine_model', models.CharField(max_length=256, verbose_name='Модель двигателя')),
                ('engine_factory_number', models.CharField(max_length=256, verbose_name='Зав. № двигателя')),
                ('transmission_model', models.CharField(max_length=256, verbose_name='Модель трансмиссии')),
                ('transmission_factory_number', models.CharField(max_length=256, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_model', models.CharField(max_length=256, verbose_name='Модель ведущего моста')),
                ('drive_axle_factory_number', models.CharField(max_length=256, verbose_name='Зав. № ведущего моста')),
                ('steering_axle_model', models.CharField(max_length=256, verbose_name='Модель управляемого моста')),
                ('steering_axle_factory_number', models.CharField(max_length=256, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=256, verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('end_user', models.CharField(max_length=256, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=256, verbose_name='Адрес поставки (эксплуатации)')),
                ('complete_set', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('client', models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('service_company', models.ForeignKey(help_text='Сервисная компания', on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
        ),
    ]
