# Generated by Django 4.1.5 on 2023-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_silant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='complete_set',
            field=models.TextField(verbose_name='Комплектация (доп. опции)'),
        ),
    ]
