# Generated by Django 4.1.5 on 2023-01-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_silant', '0005_alter_machine_service_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reclamations',
            new_name='Reclamation',
        ),
    ]
