# Generated by Django 4.1.5 on 2023-01-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_silant', '0006_rename_reclamations_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='complete_set',
            field=models.TextField(help_text='заполните вручную', verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_model', to='my_silant.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='end_user',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='my_silant.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='machine_model', to='my_silant.machinemodel', verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='steering_axle_model', to='my_silant.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supply_contract',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(help_text='выберите из списка', on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='my_silant.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
