# Generated by Django 4.1.5 on 2023-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_silant', '0009_alter_machine_client_alter_machine_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_factory_number',
            field=models.CharField(help_text='заполните вручную', max_length=256, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='spare_parts_used',
            field=models.TextField(help_text='Перечислите использованные запасные части', verbose_name='Использованные запасные части'),
        ),
    ]
