# Generated by Django 4.1.5 on 2023-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_silant', '0010_alter_machine_drive_axle_factory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='recovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата восстановления'),
        ),
    ]
