# Generated by Django 4.0.2 on 2022-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Название категории', max_length=64, null=True, unique=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Название категории', max_length=64, null=True, unique=True, verbose_name='Категория'),
        ),
    ]
