# Generated by Django 4.0.2 on 2022-06-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_post_text_en_us_post_text_ru_post_title_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
    ]
