# Generated by Django 4.0.2 on 2022-06-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_post_title_en_us_post_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
    ]
