# Generated by Django 4.1.3 on 2022-11-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0002_recipe_cooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeCategory',
        ),
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.category')),
                ('recipeThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeCategory',
            field=models.ManyToManyField(through='RecipesApp.CategoryRecipe', to='RecipesApp.category'),
        ),
    ]
