# Generated by Django 4.1.3 on 2022-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0003_remove_recipe_recipecategory_categoryrecipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryRecipe',
            field=models.ManyToManyField(through='RecipesApp.CategoryRecipe', to='RecipesApp.recipe'),
        ),
    ]
