# Generated by Django 4.0.5 on 2022-06-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
    ]
