# Generated by Django 4.0.5 on 2022-06-27 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard', '0002_respond_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respond',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='respond',
            name='accepted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
