# Generated by Django 4.0.5 on 2022-06-28 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard', '0009_remove_post_postresponds_post_postresponds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postResponds',
        ),
        migrations.AddField(
            model_name='post',
            name='postResponds',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
