# Generated by Django 4.0.5 on 2022-06-29 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0010_remove_post_postresponds_post_postresponds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
